### ISSUE TITLE
Blank space at bottom of screen

### ISSUE THREAD

**Issue by JulianPrieber** [LinkStackOrg/winter-wonderland#1]
A blank space at the bottom of the screen I can't seem to get rid of. 

This might be caused by either the background image or the background animation. I'm not sure.

I could not get this to work properly, perhaps someone knows a solution to this.

![chrome_RKTgCn8R8Q](https://user-images.githubusercontent.com/60265788/169664427-d601bdb6-b4b7-4593-87ae-a02a95da25dc.png)

**Comment by mapstonepark** [comment]
Hey! I would love to look into this but I don't see an html file to work with in code.

**Comment by JulianPrieber** [comment]
> Hey! I would love to look into this but I don't see an html file to work with in code.

**Hi Jamal, thanks for your interest!**

This is a theme for the web application [LittleLink Custom](https://littlelink-custom.com/). Essentially, this is the HTML: https://github.com/sethcottle/littlelink. This is what this application is forked from, although I'm not sure if the CSS will still work with it.

The actual page runs on Laravel Blade/PHP https://github.com/JulianPrieber/littlelink-custom/blob/main/resources/views/littlelink.blade.php.

If you still want to look into this, you can download the web app from [here](https://littlelink-custom.com/download). Installation should be fairly straight forward and pretty much works like installing WordPress minus the database.
