### ISSUE TITLE
Error when loading theme to my linksite self hosted. 

### ISSUE THREAD

**Issue by aidanarredondo** [LinkStackOrg/winter-wonderland#5]
After installing the theme on my site I got an error for that states "winter-wonderland-1.6.extra.custom-head was not found. Did you mean winter-wonderland-1.6.extra.custom-head?"

When I update the file name to the name it mentions in the previous error, it sends an error about "winter-wonderland-1.6.extra.custom-head was not found. Are you sure the view exists and is a .blade.php file?"

Full issue part 1 on [Flare](https://flareapp.io/share/87nL1zom)
Full issue part 2 on [Flare](https://flareapp.io/share/V7jA6NkP)

**Comment by lastsamurai26** [comment]
Please delete the version out of the foldername.
How did you upload the theme ? 
Did you upload the theme via uploader ?

**Comment by aidanarredondo** [comment]
I tired using the uploader but I use a webhost so the rm -f is not avilable as its in directadmin. I just uploaded it via ftp then extracted and removed the zip.

**Comment by lastsamurai26** [comment]
ok, please delete the v1.6 from the folder 
so it should only named winter-wonderland

**Comment by Aidan-A-2008** [comment]
Ok I'll try removing version number and see if this fixes the theme.

**Comment by aidanarredondo** [comment]
Ok that seems to have fixed it. Thanks
